spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver    
    password:${DB:DB_PASSWORD root}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/tourbookingdb2}
    username: ${DB_USER:root}